events {}

http {
    server {
        listen 80;

        # Forwarding headers sent to all upstream requests
        # this is required for correct identification in auth server 
        proxy_set_header X-Forwarded-URI $request_uri;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;

        # Internal auth subrequest -- auth here is docker container internal name
        location = /auth-check {
            internal;
            proxy_pass http://auth:4000/verify;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
        }

        # Redirect unauthenticated requests to the auth server login page
        location @login {
            # Scheme and host part are required if you're serving on a non-standard port
            return 302 $scheme://$http_host/auth/login?redirect_to=$request_uri;
        }

        # All auth server endpoints: login, logout, static assets
        # This must be supplied in auth server configuration, e.g. as an env:
        location /auth/ {
            proxy_pass http://auth:4000/;
        }

        #======================================================================
        # Example protected resources below:

        # Protected reverse-proxied backend app 
        # (whoami echoes request headers including X-Auth-User)
        location /app/ {
            auth_request /auth-check;
            error_page 401 = @login;
            auth_request_set $auth_user $upstream_http_x_auth_user;
            proxy_set_header X-Auth-User $auth_user;
            proxy_pass http://backend/;
        }

        # Protected static files served by nginx itself
        location /files/ {
            auth_request /auth-check;
            error_page 401 = @login;
            alias /var/www/static/;
            try_files $uri $uri/ =404;
        }
    }
}
